definitions:
  Category:
    properties:
      displayName:
        example: Televisions and Projectors
        type: string
      name:
        example: televisions-projectors
        type: string
      teaserImage:
        $ref: '#/definitions/ImageFamily'
    required:
    - name
    - displayName
  CategoryList:
    properties:
      categories:
        items:
          $ref: '#/definitions/Category'
        type: array
    required:
    - categories
    type: object
  Image:
    properties:
      externalUrl:
        example: //sonyglobal.scene7.com/is/image/gwtprod/aa67d598b260ba824817f9f8aa761c0e?fmt=png-alpha
        format: url
        type: string
    required:
    - externalUrl
  ImageFamily:
    properties:
      desktop:
        $ref: '#/definitions/Image'
    required:
    - desktop
  SearchResponse:
    properties:
      searchResponse:
        $ref: '#/definitions/SearchResponseDetails'
    required:
    - searchResponse
    type: object
  SearchResponseDetails:
    properties:
      count:
        description: Number of results available for the given search term and parameters.
          This attribute can be used to understand if more results are available and
          if it is therefore useful to execute another query to get additional results.
        example: 3456
        type: integer
      end:
        description: Indicates the index of the last result included in the search
          response. Useful for retrieving the next page of results.
        example: 10
        type: integer
      results:
        $ref: '#/definitions/SearchResults'
      start:
        description: Indicates  the index of the first result included in the search
          response.
        example: 5
        type: integer
    required:
    - count
    - start
    - end
    - results
    type: object
  SearchResults:
    properties:
      description:
        description: Snippet that can be used below the search result. Contains either
          the first words of the target URL or an excerpt of the content with highlights.
          Highlighted words will be surrounded by <em> HTML tags.
        example: This description can be used as snippet for this result.
        type: string
      title:
        example: Title of the search result
        type: string
      type:
        enum:
        - faq
        - document
        - model
        - tutorial
        - download
        example: faq
        type: string
      url:
        description: URL of the search result
        example: http://sony-eur-eu-en-web--eur.custhelp.com/app/answers/detail/a_id/100281
        format: url
        type: string
    required:
    - type
    - title
    - url
    type: object
  Suggestion:
    properties:
      name:
        example: DSC-HX350
        type: string
      url:
        description: Partial URL of the product page for this model (No host name).
        example: /electronics/support/compact-cameras-dschx-series/dsc-hx350
        type: string
    required:
    - name
    - url
    type: object
  Suggestions:
    properties:
      suggestions:
        items:
          $ref: '#/definitions/Suggestion'
        type: array
    required:
    - suggestions
    type: object
host: www.sony.co.uk
info:
  contact:
    email: thibaut.bodart@sony.com
  description: Support Categories API
  title: Sony Support API
  version: 1.0.0
paths:
  /api/content/support/{locale}/categories:
    get:
      description: "Returns all the top level categories of the support catalogue.
        \n"
      operationId: Top Categories
      parameters:
      - description: Locale of the web site
        enum:
        - en_GB
        - fr_FR
        - en_SG
        in: path
        name: locale
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: list of all the top level categories
          schema:
            $ref: '#/definitions/CategoryList'
        "400":
          description: no content returned in case the locale provided is not known
      summary: top level categories
      tags:
      - Categories
  /api/content/support/{locale}/categories/{category}:
    get:
      description: "Returns all the top level categories of the support catalogue.
        \n"
      operationId: Sub Categories
      parameters:
      - description: Locale of the web site
        enum:
        - en_GB
        - fr_FR
        - en_SG
        in: path
        name: locale
        required: true
        type: string
      - description: Category of the support catalogue <meqa Category.name>
        in: path
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: list of all the sub categories
          schema:
            $ref: '#/definitions/CategoryList'
        "400":
          description: no content returned in case the locale provided is not known
      summary: sub categories
      tags:
      - Categories
  /api/content/support/{locale}/suggest:
    get:
      description: "Returns suggested models matching the query parameter. \n"
      operationId: Model Suggestions
      parameters:
      - description: Model prefix
        in: query
        name: query
        required: true
        type: string
      - description: Locale of the web site
        enum:
        - en_GB
        - fr_FR
        - en_SG
        in: path
        name: locale
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: list of the top 5 suggestions matching the query
          schema:
            $ref: '#/definitions/Suggestions'
        "400":
          description: no content returned in case the locale provided is not correct
      summary: model suggestions
      tags:
      - Suggest
  /api/content/support/search:
    get:
      description: Organic search API for all content types
      operationId: Search
      parameters:
      - description: Search term. Can be composed of multiple words.
        in: query
        name: query
        required: true
        type: string
      - enum:
        - en_GB
        - fr_FR
        - de_DE
        - fr_BE
        - nl_BE
        - en_SG
        - en_AP
        in: query
        name: locale
        required: true
        type: string
      - default: 5
        description: Number of results to be returned by the API.
        in: query
        name: num
        type: integer
      - description: Type of the results to be returned by the API.
        enum:
        - faq
        - document
        - download
        - model
        - tutorial
        in: query
        name: type
        type: string
      - default: 1
        description: Index of the first result to return. This parameter is useful
          to build paging.
        in: query
        name: start
        type: integer
      - default: false
        description: If set to 'true', the Search API will also look for matches in
          the subdocuments. E.g. The pages of the help-guides are considered as subdocuments.  Those
          matches are returned as sub-results of a specific result.
        in: query
        name: searchInSubDocuments
        type: boolean
      - default: true
        description: Defines whether the Search API will try to infer the context
          from the search term. For example, a search for 'ILCE-6000' will understand
          that the context is this specific model and will return a best match section
          in the response. In case of best match, the results are retrieved based
          on the context that has been infered from the query term. (We are planning
          to rename this parameter to inferContext for consistency reasons)
        in: query
        name: infer-context
        type: boolean
      - description: If the value is 'cc-agent', the API will return internal FAQs
          that should not be visible on the web site for regular customers. Please
          note that if this parameter is defined, the API will validate the IP of
          the caller to make sure that the request is coming from one of the authorized
          CRM platforms.
        enum:
        - cc-agent
        in: query
        name: accessLevel
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Search Response
          schema:
            $ref: '#/definitions/SearchResponse'
        "400":
          description: no content returned in case the locale provided is not known
      summary: search
      tags:
      - Search
swagger: "2.0"
